/**
 * Single source of truth for AI provider metadata (9router-style), shared by
 * Integrations (connect UI + config + test) and Fusion (catalog). Pure data,
 * safe on server + client. Only `apikey`/local providers — no OAuth/cookie/media.
 *
 * `format` selects the request/validate shape (OpenAI-compatible vs Anthropic).
 * `validatePath` is appended to baseUrl for a lightweight connection test.
 */
export type ProviderFormat = "openai" | "anthropic";

export type AiProviderCategory =
  | "AI Providers"
  | "OpenAI-compatible"
  | "Chinese Providers"
  | "Local";

export type AiProviderEntry = {
  id: string;
  name: string;
  category: AiProviderCategory;
  display: { textIcon: string; color: string; website: string; apiKeyUrl?: string };
  transport: { baseUrl: string; format: ProviderFormat; validatePath: string };
  /** Requires an API key (false for local runtimes). */
  requiresKey: boolean;
  /** A local runtime (no key, localhost). */
  local: boolean;
  /** User must supply the baseUrl (custom / Azure). */
  baseUrlRequired?: boolean;
};

export const AI_PROVIDER_REGISTRY: AiProviderEntry[] = [
  // ── Major AI Providers ──────────────────────────────────────────────────────
  { id: "openai",      name: "OpenAI",            category: "AI Providers", display: { textIcon: "OA",  color: "#10A37F", website: "https://openai.com",                apiKeyUrl: "https://platform.openai.com/api-keys" },                transport: { baseUrl: "https://api.openai.com/v1",                               format: "openai",    validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "anthropic",   name: "Anthropic",          category: "AI Providers", display: { textIcon: "AN",  color: "#D97757", website: "https://anthropic.com",              apiKeyUrl: "https://console.anthropic.com/settings/keys" },           transport: { baseUrl: "https://api.anthropic.com/v1",                            format: "anthropic", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "google",      name: "Google AI (Gemini)", category: "AI Providers", display: { textIcon: "GG",  color: "#4285F4", website: "https://ai.google.dev",              apiKeyUrl: "https://aistudio.google.com/apikey" },                    transport: { baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai", format: "openai",    validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "xai",         name: "xAI (Grok)",         category: "AI Providers", display: { textIcon: "XAI", color: "#111111", website: "https://x.ai",                      apiKeyUrl: "https://console.x.ai" },                                  transport: { baseUrl: "https://api.x.ai/v1",                                     format: "openai",    validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "deepseek",    name: "DeepSeek",            category: "AI Providers", display: { textIcon: "DS",  color: "#4D6BFE", website: "https://deepseek.com",              apiKeyUrl: "https://platform.deepseek.com/api_keys" },                transport: { baseUrl: "https://api.deepseek.com/v1",                             format: "openai",    validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "groq",        name: "Groq",                category: "AI Providers", display: { textIcon: "GQ",  color: "#F55036", website: "https://groq.com",                  apiKeyUrl: "https://console.groq.com/keys" },                         transport: { baseUrl: "https://api.groq.com/openai/v1",                          format: "openai",    validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "mistral",     name: "Mistral AI",          category: "AI Providers", display: { textIcon: "MI",  color: "#FF7000", website: "https://mistral.ai",                apiKeyUrl: "https://console.mistral.ai/api-keys" },                   transport: { baseUrl: "https://api.mistral.ai/v1",                               format: "openai",    validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "cohere",      name: "Cohere",              category: "AI Providers", display: { textIcon: "CO",  color: "#39594D", website: "https://cohere.com",                apiKeyUrl: "https://dashboard.cohere.com/api-keys" },                 transport: { baseUrl: "https://api.cohere.ai/compatibility/v1",                  format: "openai",    validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "perplexity",  name: "Perplexity",          category: "AI Providers", display: { textIcon: "PP",  color: "#20808D", website: "https://www.perplexity.ai",         apiKeyUrl: "https://www.perplexity.ai/settings/api" },                transport: { baseUrl: "https://api.perplexity.ai",                               format: "openai",    validatePath: "/models" }, requiresKey: true,  local: false },
  // ── OpenAI-compatible: Aggregators & Inference Clouds ─────────────────────
  { id: "openrouter",          name: "OpenRouter",         category: "OpenAI-compatible", display: { textIcon: "OR",  color: "#F97316", website: "https://openrouter.ai",                      apiKeyUrl: "https://openrouter.ai/settings/keys" },                    transport: { baseUrl: "https://openrouter.ai/api/v1",                 format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "together",            name: "Together AI",        category: "OpenAI-compatible", display: { textIcon: "TG",  color: "#0F6FFF", website: "https://together.ai",                        apiKeyUrl: "https://api.together.ai/settings/api-keys" },              transport: { baseUrl: "https://api.together.xyz/v1",                  format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "fireworks",           name: "Fireworks AI",       category: "OpenAI-compatible", display: { textIcon: "FW",  color: "#7B2EF2", website: "https://fireworks.ai",                       apiKeyUrl: "https://fireworks.ai/account/api-keys" },                  transport: { baseUrl: "https://api.fireworks.ai/inference/v1",        format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "cerebras",            name: "Cerebras",           category: "OpenAI-compatible", display: { textIcon: "CB",  color: "#FF4F00", website: "https://cerebras.ai",                        apiKeyUrl: "https://cloud.cerebras.ai/platform" },                     transport: { baseUrl: "https://api.cerebras.ai/v1",                   format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "hyperbolic",          name: "Hyperbolic",         category: "OpenAI-compatible", display: { textIcon: "HY",  color: "#00D4FF", website: "https://hyperbolic.xyz",                     apiKeyUrl: "https://app.hyperbolic.xyz/settings" },                    transport: { baseUrl: "https://api.hyperbolic.xyz/v1",                format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "nebius",              name: "Nebius AI",          category: "OpenAI-compatible", display: { textIcon: "NB",  color: "#6C5CE7", website: "https://nebius.com",                         apiKeyUrl: "https://studio.nebius.com/settings/api-keys" },            transport: { baseUrl: "https://api.studio.nebius.ai/v1",              format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "siliconflow",         name: "SiliconFlow",        category: "OpenAI-compatible", display: { textIcon: "SF",  color: "#5B6EF5", website: "https://cloud.siliconflow.com",              apiKeyUrl: "https://cloud.siliconflow.com/account/ak" },               transport: { baseUrl: "https://api.siliconflow.com/v1",               format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "nvidia",              name: "NVIDIA NIM",         category: "OpenAI-compatible", display: { textIcon: "NV",  color: "#76B900", website: "https://developer.nvidia.com/nim",           apiKeyUrl: "https://build.nvidia.com/settings/api-keys" },             transport: { baseUrl: "https://integrate.api.nvidia.com/v1",          format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "chutes",              name: "Chutes AI",          category: "OpenAI-compatible", display: { textIcon: "CH",  color: "#374151", website: "https://chutes.ai",                          apiKeyUrl: "https://chutes.ai/app/api" },                               transport: { baseUrl: "https://llm.chutes.ai/v1",                     format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "vercel-ai-gateway",   name: "Vercel AI Gateway",  category: "OpenAI-compatible", display: { textIcon: "VG",  color: "#111827", website: "https://vercel.com/dashboard/~/ai-gateway",  apiKeyUrl: "https://vercel.com/dashboard/~/ai-gateway" },              transport: { baseUrl: "https://ai-gateway.vercel.sh/v1",              format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "byteplus",            name: "BytePlus ModelArk",  category: "OpenAI-compatible", display: { textIcon: "BP",  color: "#2563EB", website: "https://console.byteplus.com",               apiKeyUrl: "https://console.byteplus.com/ark/region:ark+ap-southeast-1/apiKey" }, transport: { baseUrl: "https://ark.ap-southeast.bytepluses.com/api/coding/v3", format: "openai", validatePath: "/models" }, requiresKey: true, local: false },
  { id: "opencode-go",         name: "OpenCode Go",        category: "OpenAI-compatible", display: { textIcon: "OC",  color: "#E87040", website: "https://opencode.ai",                        apiKeyUrl: "https://opencode.ai/auth" },                                transport: { baseUrl: "https://opencode.ai/zen/go/v1",                format: "openai", validatePath: "/models" }, requiresKey: true,  local: false },
  { id: "azure-openai",        name: "Azure OpenAI",       category: "OpenAI-compatible", display: { textIcon: "AZ",  color: "#0078D4", website: "https://azure.microsoft.com",               apiKeyUrl: "https://portal.azure.com" },                               transport: { baseUrl: "",                                             format: "openai", validatePath: "/models" }, requiresKey: true,  local: false, baseUrlRequired: true },
  { id: "custom",              name: "Custom (OpenAI-compatible)", category: "OpenAI-compatible", display: { textIcon: "CU", color: "#64748B", website: "" },                                  transport: { baseUrl: "",                                             format: "openai", validatePath: "/models" }, requiresKey: true,  local: false, baseUrlRequired: true },
  // ── OpenAI-compatible: More Providers ─────────────────────────────────────
  { id: "blackbox",  name: "Blackbox AI",  category: "OpenAI-compatible", display: { textIcon: "BB",  color: "#5B5FEF", website: "https://blackbox.ai",      apiKeyUrl: "https://www.blackbox.ai/api-management" }, transport: { baseUrl: "https://api.blackbox.ai",                   format: "openai", validatePath: "/models" }, requiresKey: true, local: false },
  { id: "commandcode", name: "Command Code", category: "OpenAI-compatible", display: { textIcon: "CC", color: "#111111", website: "https://commandcode.ai",  apiKeyUrl: "https://commandcode.ai/studio" },          transport: { baseUrl: "https://api.commandcode.ai/alpha",          format: "openai", validatePath: "/models" }, requiresKey: true, local: false },
  // ── Chinese Providers ───────────────────────────────────────────────────────
  { id: "alicode",         name: "Alibaba Cloud AI",         category: "Chinese Providers", display: { textIcon: "ALi", color: "#FF6A00", website: "https://bailian.console.aliyun.com",            apiKeyUrl: "https://bailian.console.aliyun.com/?apiKey=1" },                         transport: { baseUrl: "https://coding.dashscope.aliyuncs.com/v1",                       format: "openai",    validatePath: "/models" }, requiresKey: true, local: false },
  { id: "alicode-intl",    name: "Alibaba Intl",             category: "Chinese Providers", display: { textIcon: "ALi", color: "#FF6A00", website: "https://modelstudio.console.alibabacloud.com",   apiKeyUrl: "https://modelstudio.console.alibabacloud.com/?apiKey=1" },           transport: { baseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1",                 format: "openai",    validatePath: "/models" }, requiresKey: true, local: false },
  { id: "glm",             name: "GLM Coding (Intl)",        category: "Chinese Providers", display: { textIcon: "GL",  color: "#2563EB", website: "https://open.bigmodel.cn",                       apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys" },                      transport: { baseUrl: "https://api.z.ai/api/anthropic/v1",                              format: "anthropic", validatePath: "/models" }, requiresKey: true, local: false },
  { id: "glm-cn",          name: "GLM (China)",              category: "Chinese Providers", display: { textIcon: "GC",  color: "#DC2626", website: "https://open.bigmodel.cn",                       apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys" },                      transport: { baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",                    format: "openai",    validatePath: "/models" }, requiresKey: true, local: false },
  { id: "kimi",            name: "Kimi (Moonshot)",          category: "Chinese Providers", display: { textIcon: "KM",  color: "#1E3A8A", website: "https://platform.moonshot.ai",                   apiKeyUrl: "https://platform.moonshot.ai/console/api-keys" },                    transport: { baseUrl: "https://api.kimi.com/coding/v1",                                 format: "anthropic", validatePath: "/models" }, requiresKey: true, local: false },
  { id: "minimax",         name: "Minimax Coding (Intl)",    category: "Chinese Providers", display: { textIcon: "MM",  color: "#7C3AED", website: "https://www.minimaxi.com",                       apiKeyUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key" }, transport: { baseUrl: "https://api.minimax.io/anthropic/v1",                   format: "anthropic", validatePath: "/models" }, requiresKey: true, local: false },
  { id: "minimax-cn",      name: "Minimax (China)",          category: "Chinese Providers", display: { textIcon: "MC",  color: "#DC2626", website: "https://www.minimaxi.com",                       apiKeyUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key" }, transport: { baseUrl: "https://api.minimaxi.com/anthropic/v1",                  format: "anthropic", validatePath: "/models" }, requiresKey: true, local: false },
  { id: "volcengine-ark",  name: "Volcengine Ark",           category: "Chinese Providers", display: { textIcon: "ARK", color: "#1677FF", website: "https://console.volcengine.com",                 apiKeyUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey" },  transport: { baseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3",                format: "openai",    validatePath: "/models" }, requiresKey: true, local: false },
  { id: "xiaomi-mimo",     name: "Xiaomi MiMo",              category: "Chinese Providers", display: { textIcon: "XM",  color: "#FF6900", website: "https://xiaomimimo.com",                         apiKeyUrl: "https://xiaomimimo.com" },                                           transport: { baseUrl: "https://api.xiaomimimo.com/v1",                                  format: "openai",    validatePath: "/models" }, requiresKey: true, local: false },
  { id: "xiaomi-tokenplan", name: "Xiaomi MiMo (Token Plan)", category: "Chinese Providers", display: { textIcon: "XT", color: "#FF6700", website: "https://mimo.xiaomi.com",                       apiKeyUrl: "https://mimo.xiaomi.com" },                                          transport: { baseUrl: "https://token-plan-sgp.xiaomimimo.com/v1",                       format: "openai",    validatePath: "/models" }, requiresKey: true, local: false },
  // ── Local Runtimes ──────────────────────────────────────────────────────────
  { id: "ollama",   name: "Ollama",    category: "Local", display: { textIcon: "OL", color: "#111111", website: "https://ollama.com"   }, transport: { baseUrl: "http://localhost:11434/v1", format: "openai", validatePath: "/models" }, requiresKey: false, local: true },
  { id: "lmstudio", name: "LM Studio", category: "Local", display: { textIcon: "LM", color: "#7C3AED", website: "https://lmstudio.ai"  }, transport: { baseUrl: "http://localhost:1234/v1",  format: "openai", validatePath: "/models" }, requiresKey: false, local: true },
];

export function getAiProvider(id: string): AiProviderEntry | undefined {
  return AI_PROVIDER_REGISTRY.find((p) => p.id === id);
}

export const AI_PROVIDER_IDS = AI_PROVIDER_REGISTRY.map((p) => p.id);
